// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuvkdbhfkzozeuxtedob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dmtkYmhma3pvemV1eHRlZG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTA1NzcsImV4cCI6MjA1OTUyNjU3N30.6nwty9WX6t09fBxG78fXLpPViH-8LShhtTg_YdTHUfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);